name: Release Docker Images for RC

on:
  push:
    branches:
      - rc/**


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  determine-tags:
    runs-on: ubuntu-latest

    outputs:
      TAGS_WESEEK: ${{ steps.meta-weseek.outputs.tags }}
      TAGS_GROWILABS: ${{ steps.meta-growilabs.outputs.tags }}

    steps:
    - uses: actions/checkout@v4

    - name: Retrieve information from package.json
      uses: myrotvorets/info-from-package-json-action@v2.0.2
      id: package-json

    - name: Docker meta for weseek/growi
      uses: docker/metadata-action@v5
      id: meta-weseek
      with:
        images: docker.io/weseek/growi
        sep-tags: ','
        tags: |
          type=raw,value=latest
          type=semver,value=${{ needs.create-github-release.outputs.RELEASED_VERSION }},pattern={{major}}
          type=semver,value=${{ needs.create-github-release.outputs.RELEASED_VERSION }},pattern={{major}}.{{minor}}
          type=semver,value=${{ needs.create-github-release.outputs.RELEASED_VERSION }},pattern={{major}}.{{minor}}.{{patch}}

    - name: Docker meta for growilabs/growi
      uses: docker/metadata-action@v5
      id: meta-growilabs
      with:
        images: docker.io/growilabs/growi
        sep-tags: ','
        tags: |
          type=raw,value=latest
          type=semver,value=${{ needs.create-github-release.outputs.RELEASED_VERSION }},pattern={{major}}
          type=semver,value=${{ needs.create-github-release.outputs.RELEASED_VERSION }},pattern={{major}}.{{minor}}
          type=semver,value=${{ needs.create-github-release.outputs.RELEASED_VERSION }},pattern={{major}}.{{minor}}.{{patch}}


  build-image-rc:
    uses: growilabs/growi/.github/workflows/reusable-app-build-image.yml@master
    with:
      image-name: growilabs/growi
      tag-temporary: latest-rc
    secrets:
      AWS_ROLE_TO_ASSUME_FOR_OIDC: ${{ secrets.AWS_ROLE_TO_ASSUME_FOR_OIDC }}


  publish-app-image-for-growilabs:
    needs: [determine-tags, build-image-rc]

    uses: growilabs/growi/.github/workflows/reusable-app-create-manifests.yml@master
    with:
      tags: ${{ needs.determine-tags.outputs.TAGS_GROWILABS }}
      registry: docker.io
      image-name: 'growilabs/growi'
      docker-registry-username: 'growimoogle'
      tag-temporary: latest-rc
    secrets:
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD_GROWIMOOGLE }}

  publish-app-image-for-weseek:
    needs: [determine-tags, build-image-rc]

    uses: growilabs/growi/.github/workflows/reusable-app-create-manifests.yml@master
    with:
      tags: ${{ needs.determine-tags.outputs.TAGS_WESEEK }}
      registry: docker.io
      image-name: 'growilabs/growi'
      docker-registry-username: 'wsmoogle'
      tag-temporary: latest-rc
    secrets:
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
